---
- name: Install packages for avahi
  dnf:
    name:
      - avahi

- name: Enable avahi service
  service:
    name: avahi-daemon.service
    state: started
    enabled: yes

- name: Enable avahi name resolution
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^hosts:'
    line: "hosts: files mdns4_minimal [NOTFOUND=return] dns myhostname"

- name: Configure firewall
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items:
    - mdns