---
- name: Add a sambda server config file
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    validate: 'testparm -s %s'

# List samba SELinux booleans: sudo semanage boolean -l | grep samba
- name: Enable samba to read system directories
  seboolean:
    name: samba_export_all_ro
    state: yes
    persistent: yes

- name: Start samba service
  service:
    name: smb
    state: started
    enabled: yes
